info:
  component: Config Server
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/davidmulligan/RSP-Portal-Service
management:
  context_path: /admin