info:
  component: Config Server
server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/myorg/{application}
management:
  context_path: /admin